const FETCH_BUDGET = 'FETCH_BUDGET';
const FETCH_CUSTOMER = 'FETCH_CUSTOMER';
const FETCH_TASK_PROGRESS = 'FETCH_TASK_PROGRESS';
const FETCH_TOTAL_PROFIT = 'FETCH_TOTAL_PROFIT';
const FETCH_MANAGER = 'FETCH_MANAGER';
const FETCH_STUDENT = 'FETCH_STUDENT';
const FIND_STUDENT = 'FIND_STUDENT';
const FETCH_PROJECT = 'FETCH_PROJECT';
const FETCH_GROUP = 'FETCH_GROUP';
const FETCH_LANGUAGE = 'FETCH_LANGUAGE';
const FETCH_USER = 'FETCH_USER';
const FETCH_EMPLOYEE = 'FETCH_EMPLOYEE';
const FETCH_AUTH = 'FETCH_AUTH';

export const KEY_QUERIES = {
  [FETCH_CUSTOMER]: FETCH_CUSTOMER,
  [FETCH_MANAGER]: FETCH_MANAGER,
  [FETCH_STUDENT]: FETCH_STUDENT,
  [FETCH_PROJECT]: FETCH_PROJECT,
  [FETCH_AUTH]: FETCH_AUTH,
  [FETCH_GROUP]: FETCH_GROUP,
  [FETCH_LANGUAGE]: FETCH_LANGUAGE,
  [FETCH_USER]: FETCH_USER,
  [FETCH_EMPLOYEE]: FETCH_EMPLOYEE,
};
