const FETCH_CUSTOMER = 'FETCH_CUSTOMER';
const FETCH_MANAGER = 'FETCH_MANAGER';
const FETCH_PROJECT = 'FETCH_PROJECT';
const FETCH_GROUP = 'FETCH_GROUP';
const FETCH_LANGUAGE = 'FETCH_LANGUAGE';
const FETCH_USER = 'FETCH_USER';
const FETCH_EMPLOYEE = 'FETCH_EMPLOYEE';
const FETCH_AUTH = 'FETCH_AUTH';
const FETCH_PROJECT_MEMBER = 'FETCH_PROJECT_MEMBER';
const FETCH_PROJECT_ISSUE = 'FETCH_PROJECT_ISSUE';
const FETCH_ISSUE = 'FETCH_ISSUE';
const FETCH_PARENT_ISSUE = 'FETCH_PARENT_ISSUE';
const FETCH_TRACKER_ISSUE_STATISTIC = 'FETCH_TRACKER_ISSUE_STATISTIC';
const FETCH_PRIORITY_ISSUE_STATISTIC = 'FETCH_PRIORITY_ISSUE_STATISTIC';
const FETCH_TRACKER = 'FETCH_TRACKER';
const FETCH_TARGET_VERSION = 'FETCH_TARGET_VERSION';
const FETCH_ISSUE_STATUS = 'FETCH_ISSUE_STATUS';
const FETCH_PROJECT_POSITION = 'FETCH_PROJECT_POSITION';
const FETCH_PROJECT_MEMBER_ACTIVITY = 'FETCH_PROJECT_MEMBER_ACTIVITY';
const FETCH_MEMBER_PROJECT = 'FETCH_MEMBER_PROJECT';
const FETCH_ROLE = 'FETCH_ROLE';
const FETCH_PERMISSION = 'FETCH_PERMISSION';
const FETCH_POSITION = 'FETCH_POSITION';

export const KEY_QUERIES = {
  [FETCH_CUSTOMER]: FETCH_CUSTOMER,
  [FETCH_MANAGER]: FETCH_MANAGER,
  [FETCH_PROJECT]: FETCH_PROJECT,
  [FETCH_AUTH]: FETCH_AUTH,
  [FETCH_GROUP]: FETCH_GROUP,
  [FETCH_LANGUAGE]: FETCH_LANGUAGE,
  [FETCH_USER]: FETCH_USER,
  [FETCH_EMPLOYEE]: FETCH_EMPLOYEE,
  [FETCH_TRACKER_ISSUE_STATISTIC]: FETCH_TRACKER_ISSUE_STATISTIC,
  [FETCH_PRIORITY_ISSUE_STATISTIC]: FETCH_PRIORITY_ISSUE_STATISTIC,
  [FETCH_PROJECT_MEMBER]: FETCH_PROJECT_MEMBER,
  [FETCH_PROJECT_ISSUE]: FETCH_PROJECT_ISSUE,
  [FETCH_ISSUE]: FETCH_ISSUE,
  [FETCH_TRACKER]: FETCH_TRACKER,
  [FETCH_PARENT_ISSUE]: FETCH_PARENT_ISSUE,
  [FETCH_TARGET_VERSION]: FETCH_TARGET_VERSION,
  [FETCH_ISSUE_STATUS]: FETCH_ISSUE_STATUS,
  [FETCH_PROJECT_POSITION]: FETCH_PROJECT_POSITION,
  [FETCH_PROJECT_MEMBER_ACTIVITY]: FETCH_PROJECT_MEMBER_ACTIVITY,
  [FETCH_MEMBER_PROJECT]: FETCH_MEMBER_PROJECT,
  [FETCH_MEMBER_PROJECT]: FETCH_MEMBER_PROJECT,
  [FETCH_ROLE]: FETCH_ROLE,
  [FETCH_PERMISSION]: FETCH_PERMISSION,
  [FETCH_POSITION]: FETCH_POSITION,
};
